//! Pure-Rust computer-vision primitives for the nestris engine.
//!
//! Every routine here replicates the exact numeric behavior of the OpenCV /
//! numpy call it replaces, because the engine's thresholds were tuned against
//! those implementations. Each module carries golden tests against outputs
//! generated by the original library (see `testdata/cv/` at the workspace
//! root, regenerated by `tools/gen_cv_goldens.py`).
//!
//! This crate is I/O-free and allocation-conscious: it must compile for
//! `wasm32-unknown-unknown` without features.

pub mod color;
pub mod components;
pub mod image;
pub mod morphology;
pub mod ncc;
pub mod resize;
pub mod rng;
pub mod stats;
pub mod threshold;

pub use image::Image;
